# Generated by Django 3.0.1 on 2020-01-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20191230_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=60)),
                ('type_en', models.CharField(max_length=60)),
                ('type_sort', models.PositiveSmallIntegerField(default=0)),
                ('type_mid', models.PositiveSmallIntegerField(default=1)),
                ('type_pid', models.PositiveSmallIntegerField(default=0)),
                ('type_status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('vod_id', models.AutoField(primary_key=True, serialize=False)),
                ('vod_name', models.CharField(max_length=255, unique=True)),
                ('vod_sub', models.CharField(max_length=60)),
                ('vod_pic', models.CharField(max_length=255)),
                ('vod_class', models.CharField(max_length=60)),
                ('vod_time_add', models.DateTimeField(auto_now_add=True)),
                ('vod_time_hits', models.DateTimeField(auto_now=True)),
                ('vod_play_url', models.CharField(max_length=255)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Type')),
                ('vod_ower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
    ]
